module(load="imtcp")
input(type="imtcp" port="514")
 
template(name="RemoteLogs" type="string"
  string="/var/log/remote/%HOSTNAME%/%PROGRAMNAME%.log")
 
if $fromhost-ip != '127.0.0.1' then {
  action(type="omfile" dynaFile="RemoteLogs")
  stop
}
sudo mkdir -p /var/log/remote
sudo chown syslog:adm /var/log/remote   # adjust ownership to the rsyslog service account
sudo systemctl restart rsyslog
 
sudo firewall-cmd --add-port=514/tcp --permanent
sudo firewall-cmd --reload

