[Interface]
Address = 10.100.0.1/24
PrivateKey = <edge01_private_key>
 
[Peer]
# backend02 (Azure)
PublicKey = <backend02_public_key>
Endpoint = 158.158.37.102:51820
AllowedIPs = 10.100.0.2/32
PersistentKeepalive = 25

